### ISSUE TITLE
Fails to build book

### ISSUE THREAD

**Issue by psybers** [uds-se/fuzzingbook#110]
**Describe the bug**
Attempting to build the book with the `make book` command results in an assertion error.

**To Reproduce**
1. Clone repository
2. Execute `make book`

**Expected behavior**
A book is built (a PDF? HTML+PDF+notebook? it isn't entirely clear what that target builds).

**Screenshots**
````python
% make book
jupyter nbconvert --log-level=WARN --ExecutePreprocessor.timeout=140 --to notebook --execute --output-dir=full_notebooks notebooks/GrammarMiner.ipynb
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/usr/local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 346, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 518, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 483, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 412, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 84, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 105, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fuzzer = GrammarCoverageFuzzer(grammar)
[fuzzer.fuzz() for i in range(5)]
------------------

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/var/folders/p4/mw9cffq901v6wwg48f2n_nym0000gp/T/ipykernel_53683/3703389860.py in <module>
----> 1 fuzzer = GrammarCoverageFuzzer(grammar)
      2 [fuzzer.fuzz() for i in range(5)]

~/Downloads/fuzzingbook/notebooks/GrammarCoverageFuzzer.ipynb in __init__(self, *args, **kwargs)
     11     def __init__(self, *args, **kwargs):
     12         # invoke superclass __init__(), passing all arguments
---> 13         super().__init__(*args, **kwargs)
     14         self.reset_coverage()
     15 

~/Downloads/fuzzingbook/notebooks/GrammarFuzzer.ipynb in __init__(self, grammar, start_symbol, min_nonterminals, max_nonterminals, disp, log)
    133         self.disp = disp
    134         self.log = log
--> 135         self.check_grammar()  # Invokes is_valid_grammar()
    136 
    137 class GrammarFuzzer(GrammarFuzzer):

~/Downloads/fuzzingbook/notebooks/GrammarFuzzer.ipynb in check_grammar(self)
    138     def check_grammar(self):
    139         assert self.start_symbol in self.grammar
--> 140         assert is_valid_grammar(
    141             self.grammar,
    142             start_symbol=self.start_symbol,

AssertionError: 
AssertionError: 

make: *** [full_notebooks/GrammarMiner.ipynb] Error 1
````

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.2
 - Python 3.9.6 (via brew)
````sh
% brew info python
python@3.9: stable 3.9.6 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.9/3.9.6 (3,183 files, 56.3MB) *
  Poured from bottle on 2021-07-05 at 15:30:36
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/python@3.9.rb
License: Python-2.0
````
- installed packages:
````
% pip3.9 list       
Package                Version
---------------------- ---------
anyio                  3.3.0
appnope                0.1.2
argon2-cffi            20.1.0
astor                  0.8.1
attrs                  21.2.0
autopep8               1.5.7
backcall               0.2.0
beautifulsoup4         4.9.3
bibtexparser           1.2.0
bleach                 4.0.0
certifi                2021.5.30
cffi                   1.14.5
chardet                4.0.0
colorama               0.4.4
cycler                 0.10.0
debugpy                1.4.1
decorator              5.0.9
defusedxml             0.7.1
Deprecated             1.2.12
entrypoints            0.3
future                 0.18.2
gitdb                  4.0.7
GitPython              3.1.18
graphviz               0.17
idna                   2.10
ipdb                   0.13.9
ipykernel              6.2.0
ipython                7.26.0
ipython-genutils       0.2.0
jedi                   0.18.0
Jinja2                 3.0.1
jsonschema             3.2.0
jupyter-client         6.1.12
jupyter-core           4.7.1
jupyter-server         1.10.2
jupyter-server-mathjax 0.2.3
jupyterlab-pygments    0.1.2
kiwisolver             1.3.1
lxml                   4.6.3
Markdown               3.3.4
MarkupSafe             2.0.1
matplotlib             3.4.3
matplotlib-inline      0.1.2
mistune                0.8.4
mypy                   0.910
mypy-extensions        0.4.3
nbclient               0.5.4
nbconvert              6.1.0
nbdime                 3.1.0
nbformat               5.1.3
nbstripout             0.5.0
nest-asyncio           1.5.1
networkx               2.6.2
notebook               6.4.3
notedown               1.5.1
numpy                  1.20.3
packaging              21.0
pandas                 1.2.4
pandoc-attributes      0.1.7
pandocfilters          1.4.3
parso                  0.8.2
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.3.1
pip                    21.1.3
prometheus-client      0.11.0
prompt-toolkit         3.0.19
ptyprocess             0.7.0
pyAn                   0.1.3
pyan3                  1.1.1
pycodestyle            2.7.0
pycparser              2.20
pydot                  1.4.2
PyGithub               1.55
Pygments               2.10.0
PyJWT                  2.1.0
PyNaCl                 1.4.0
pyparsing              2.4.7
pyrsistent             0.18.0
python-dateutil        2.8.1
pytz                   2021.1
pyzmq                  22.2.1
requests               2.25.1
requests-unixsocket    0.2.0
scipy                  1.7.0
selenium               3.141.0
Send2Trash             1.8.0
setuptools             57.0.0
showast                0.2.4
six                    1.16.0
smmap                  4.0.0
sniffio                1.2.0
soupsieve              2.2.1
terminado              0.11.1
testpath               0.5.0
toml                   0.10.2
tornado                6.1
traitlets              5.0.5
typing-extensions      3.10.0.0
urllib3                1.26.6
wcwidth                0.2.5
webencodings           0.5.1
websocket-client       1.2.1
wheel                  0.36.2
wrapt                  1.12.1
````

**Comment by andreas-zeller** [comment]
"make book" creates a PDF of the book. This is experimental at best. But if the problem also occurs with "make html" (a much more supported target), let us know.
